package com.pack.shopping.cart.api.hateoas;

import org.springframework.beans.BeanUtils;
import org.springframework.hateoas.server.mvc.RepresentationModelAssemblerSupport;
import org.springframework.stereotype.Component;

import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;

import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

import com.pack.shopping.cart.api.controller.PaymentRestController;
import com.pack.shopping.cart.api.dto.PaymentDTO;
import com.pack.shopping.cart.api.entity.PaymentEntity;

@Component
public class PaymentRepresentationModelAssembler
        extends RepresentationModelAssemblerSupport<PaymentEntity, PaymentDTO> {

    /**
     * Creates a new {@link RepresentationModelAssemblerSupport} using the given
     * controller class and
     * resource type.
     */
    public PaymentRepresentationModelAssembler() {
        super(PaymentRestController.class, PaymentDTO.class);
    }

    /**
     * Coverts the Payment entity to resource
     *
     * @param entity
     */
    @Override
    public PaymentDTO toModel(PaymentEntity entity) {
        PaymentDTO resource = createModelWithId(entity.getPaymentId(), entity);
        BeanUtils.copyProperties(entity, resource);
        resource.setPaymentId(entity.getPaymentId().toString());
        // Self link generated by createModelWithId has missing api path. Therefore
        // generating additionally.
        // can be removed once fixed.
        resource.add(linkTo(
                methodOn(PaymentRestController.class).getOrdersPaymentAuthorization(entity.getPaymentId().toString()))
                .withSelfRel());
        return resource;
    }

    /**
     * Coverts the collection of Payment entities to list of resources.
     *
     * @param entities
     */
    public List<PaymentDTO> toListModel(Iterable<PaymentEntity> entities) {
        if (Objects.isNull(entities)) {
            return Collections.emptyList();
        }
        return StreamSupport.stream(entities.spliterator(), false).map(e -> toModel(e))
                .collect(Collectors.toList());
    }

}
