version: '3'
services:
 # Database Service 
  db-postgres:
    container_name: db-postgres
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommerceDB
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:  
